-- ==============================================================================
-- FRESH START: CLEANUP & REBUILD SCRIPT
-- This script will DROP ALL existing tables/functions/triggers and re-create them.
-- ==============================================================================

-- 1. CLEANUP (Drop everything to ensure a clean slate)
-- We use CASCADE to automatically remove dependent objects (like foreign keys/triggers)
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop table if exists public.api_requests cascade;
drop table if exists public.conversion_history cascade;
drop table if exists public.users_custom cascade;
drop table if exists public.plans cascade;
drop table if exists public.app_configs cascade;
drop table if exists public.profiles cascade; -- Dropping old table if it exists
drop table if exists public.conversions cascade; -- Dropping old table if it exists

-- 2. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 3. TABLES

-- Table: users_custom
create table public.users_custom (
  id uuid references auth.users not null primary key,
  email text not null,
  name text not null,
  plan text not null default 'free',
  conversions_used integer not null default 0,
  api_key text unique,
  bearer_token text,
  role text not null default 'user',
  plan_started_at timestamp with time zone,
  plan_renews_at timestamp with time zone,
  is_active boolean not null default true,
  created_at timestamp with time zone default now(),
  
  constraint username_length check (char_length(name) >= 2)
);

-- Table: conversion_history
create table public.conversion_history (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users_custom(id) not null,
  text text not null,
  qr_code_url text,
  type text not null check (type in ('url', 'text')),
  created_at timestamp with time zone default now() not null
);

-- Table: plans
create table public.plans (
  id text primary key,
  name text not null,
  price_monthly_cents integer not null,
  monthly_conversions integer not null,
  features text[] default '{}',
  is_active boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Table: app_configs
create table public.app_configs (
  id uuid default uuid_generate_v4() primary key,
  config_key text not null unique default 'global',
  is_maintenance boolean not null default false,
  enable_user_registration boolean not null default true,
  default_free_plan_limit integer not null default 10,
  conversion_reset_period text not null default 'monthly',
  maintenance_message text default 'The site is under maintenance.',
  support_email text default 'support@example.com',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Table: api_requests
create table public.api_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users_custom(id),
  api_key text,
  path text,
  status_code integer,
  created_at timestamp with time zone default now()
);

-- 4. ROW LEVEL SECURITY (RLS)

-- users_custom
alter table users_custom enable row level security;
create policy "Users can view their own profile." on users_custom for select using (auth.uid() = id);
create policy "Users can update their own profile." on users_custom for update using (auth.uid() = id);

-- conversion_history
alter table conversion_history enable row level security;
create policy "Users can view their own history." on conversion_history for select using (auth.uid() = user_id);
create policy "Users can insert their own history." on conversion_history for insert with check (auth.uid() = user_id);
create policy "Users can delete their own history." on conversion_history for delete using (auth.uid() = user_id);

-- plans
alter table plans enable row level security;
create policy "Plans are viewable by everyone." on plans for select using (true);

-- app_configs
alter table app_configs enable row level security;
create policy "Configs are viewable by everyone." on app_configs for select using (true);

-- api_requests
alter table api_requests enable row level security;
create policy "Users can view their own api requests." on api_requests for select using (auth.uid() = user_id);

-- 5. FUNCTIONS & TRIGGERS

-- Function: handle_new_user
-- Uses md5(random()) for maximum compatibility (no extensions required)
create or replace function public.handle_new_user()
returns trigger as $$
declare
  new_api_key text;
  new_bearer_token text;
begin
  -- Generate keys using standard Postgres functions (no extensions needed)
  new_api_key := 'qr_' || md5(random()::text || clock_timestamp()::text);
  new_bearer_token := 'br_' || md5(random()::text || clock_timestamp()::text) || md5(random()::text || clock_timestamp()::text);

  insert into public.users_custom (id, email, name, plan, conversions_used, is_active, api_key, bearer_token)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'full_name', new.email), 
    'free', 
    0, 
    true,
    new_api_key,
    new_bearer_token
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger: on_auth_user_created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. SEED DATA (Default Plans)
insert into public.plans (id, name, price_monthly_cents, monthly_conversions, features)
values 
  ('free', 'Free', 0, 10, '{"10 conversions/month", "Basic analytics"}'),
  ('starter', 'Starter', 900, 100, '{"100 conversions/month", "Advanced analytics", "Email support"}'),
  ('professional', 'Professional', 2900, 500, '{"500 conversions/month", "Priority support", "Custom branding"}'),
  ('business', 'Business', 7900, 2000, '{"2000 conversions/month", "24/7 Support", "API Access"}')
on conflict (id) do nothing;

-- 7. SEED DATA (Default Config)
insert into public.app_configs (config_key) values ('global') on conflict do nothing;
